"""岗位字段标签和长度限制。"""

_FIELD_LIMITS = {
    "title": 128,
    "company": 128,
    "location": 64,
    "salary": 64,
    "job_type": 32,
    "source_url": 512,
    "posted_at": 32,
    "status": 16,
}

_LABELS = {
    "title": (
        "职位名称",
        "岗位名称",
        "招聘职位名称",
        "招聘岗位名称",
        "职位名",
        "岗位名",
        "招聘职位名",
        "招聘岗位名",
        "招聘职位",
        "招聘岗位",
        "职位标题",
        "岗位标题",
        "职位",
        "岗位",
        "job title",
        "position title",
        "position name",
        "position",
        "title",
        "role",
        "job",
    ),
    "company": (
        "公司名称",
        "企业名称",
        "企业",
        "招聘公司",
        "招聘企业",
        "招聘主体",
        "所属公司",
        "所属企业",
        "公司主体",
        "企业主体",
        "用人单位",
        "任职单位",
        "雇主",
        "公司",
        "employer",
        "employer name",
        "enterprise",
        "organization",
        "organisation",
        "organization name",
        "company",
        "company name",
    ),
    "location": (
        "工作地点",
        "工作地址",
        "工作城市",
        "办公地点",
        "办公城市",
        "职位地点",
        "职位城市",
        "岗位地点",
        "所在城市",
        "工作地",
        "工作区域",
        "地点",
        "城市",
        "work location",
        "location",
        "city",
        "office",
    ),
    "salary": (
        "薪资范围",
        "薪资待遇",
        "薪酬待遇",
        "薪资福利",
        "薪酬福利",
        "薪酬范围",
        "工资待遇",
        "月薪范围",
        "年薪范围",
        "薪酬",
        "薪资",
        "月薪",
        "年薪",
        "salary range",
        "compensation",
        "salary",
        "pay",
    ),
    "job_type": (
        "招聘类型",
        "职位类型",
        "岗位类型",
        "工作性质",
        "岗位性质",
        "职位性质",
        "用工性质",
        "用工形式",
        "雇佣类型",
        "工作形式",
        "合同类型",
        "招聘形式",
        "用工类型",
        "employment type",
        "job type",
        "position type",
        "work type",
        "contract type",
    ),
    "source_url": (
        "投递链接",
        "申请链接",
        "职位链接",
        "岗位链接",
        "招聘链接",
        "官网链接",
        "官网投递链接",
        "网申地址",
        "申请网址",
        "官网地址",
        "职位详情链接",
        "详情链接",
        "链接",
        "URL",
        "apply url",
        "application url",
        "job url",
        "job link",
        "career url",
        "link",
    ),
    "posted_at": (
        "发布时间",
        "发布日期",
        "发布于",
        "posted date",
        "date posted",
        "published",
        "posted",
    ),
    "status": (
        "招聘状态",
        "职位状态",
        "岗位状态",
        "招聘进度",
        "招聘有效期",
        "状态",
        "job status",
        "hiring status",
        "status",
    ),
}

_ENGLISH_LABELS_REQUIRING_COLON = frozenset(
    {
        "job",
        "company",
        "enterprise",
        "title",
        "position",
        "role",
        "posted",
        "updated",
        "status",
        "link",
    }
)
