"""基本信息字段标签和身份识别正则。"""

_BASIC_LABELS = {
    "name": ("姓名", "名字", "真实姓名", "姓名拼音", "name", "full name", "candidate name"),
    "gender": ("性别", "gender"),
    "birth_year": ("出生年份", "出生年月", "出生日期", "生日", "出生信息", "birth"),
    "phone": (
        "手机号",
        "手机号码",
        "手机",
        "电话",
        "联系电话",
        "联系方式",
        "电话号",
        "phone",
        "mobile",
        "phone number",
        "telephone",
        "contact number",
    ),
    "email": (
        "邮箱",
        "电子邮箱",
        "电子邮件",
        "Email",
        "E-mail",
        "email",
        "mail",
        "email address",
    ),
    "city": (
        "所在城市",
        "现居城市",
        "所在地",
        "现居地",
        "现居",
        "当前城市",
        "居住地",
        "居住城市",
        "所在地城市",
        "籍贯",
        "出生地",
        "city",
        "current city",
        "current location",
        "location",
    ),
    "target_city": (
        "意向城市",
        "目标城市",
        "期望城市",
        "工作城市",
        "目标地点",
        "target city",
        "preferred location",
        "desired city",
    ),
    "job_intent": (
        "求职意向",
        "求职方向",
        "目标职位",
        "应聘职位",
        "意向职位",
        "目标岗位",
        "期望岗位",
        "期望职位",
        "职位意向",
        "career objective",
        "target role",
        "desired role",
        "objective",
    ),
    "personal_website": ("个人网站", "个人主页", "博客", "作品集", "portfolio", "website"),
    "github": ("GitHub", "Github", "github"),
}
