"""资料分区标题及其兼容别名。"""

_SECTION_ALIASES = {
    "educations": (
        "教育经历",
        "教育背景",
        "学历经历",
        "学习经历",
        "教育信息",
        "学历背景",
        "教育履历",
        "教育与培训",
        "学历信息",
        "education",
        "education background",
        "education and training",
        "education & training",
    ),
    "experiences": (
        "实习经历",
        "工作经历",
        "任职经历",
        "工作履历",
        "职业经历",
        "工作经验",
        "任职履历",
        "工作与实习",
        "经历概览",
        "实践经历",
        "科研经历",
        "任职/实习经历",
        "实习/工作经验",
        "实习/工作经历",
        "工作/实习经历",
        "professional experience",
        "experience",
        "work experience",
        "work history",
        "professional history",
        "internship experience",
        "internships",
        "employment history",
        "employment",
    ),
    "campus_experiences": (
        "校园经历",
        "学生工作",
        "社团经历",
        "校内经历",
        "校园实践",
        "学生经历",
        "校园活动",
        "校园与社团",
        "学生组织经历",
        "社会实践",
        "志愿服务",
        "campus experience",
        "campus activities",
        "student activities",
        "student leadership",
        "leadership experience",
        "extracurricular experience",
        "extracurricular activities",
        "campus involvement",
    ),
    "projects": (
        "项目经历",
        "项目经验",
        "项目实践",
        "项目履历",
        "项目经验及实践",
        "项目与实践",
        "作品与项目",
        "projects",
        "projects & practice",
        "projects and practice",
        "project & practice",
        "project experience",
        "project and practice",
        "portfolio projects",
        "selected projects",
        "project highlights",
    ),
    "skills": (
        "专业技能",
        "技能清单",
        "技能",
        "技术栈",
        "技术能力",
        "专业能力",
        "核心技能",
        "编程技能",
        "工具技能",
        "IT技能",
        "能力特长",
        "技能特长",
        "专业特长",
        "核心能力",
        "职业技能",
        "技术专长",
        "语言能力",
        "skills",
        "technical skills",
        "technical abilities",
        "technical expertise",
        "technical proficiencies",
        "skills & certifications",
        "skills and certifications",
        "programming languages",
        "tools & technologies",
        "skills & tools",
        "competencies",
    ),
    "awards": (
        "荣誉奖项",
        "获奖情况",
        "获奖经历",
        "奖项",
        "荣誉",
        "奖励情况",
        "awards",
        "honors",
        "certifications",
        "certificates",
    ),
    "summary": (
        "个人总结",
        "自我评价",
        "个人总结/自我评价",
        "个人总结 / 自我评价",
        "个人简介",
        "个人概述",
        "职业简介",
        "个人亮点",
        "职业总结",
        "职业目标",
        "summary",
        "profile",
        "career summary",
        "professional summary",
        "professional profile",
        "about me",
    ),
}

# 这些标题不是表单分区，但出现时应结束上一分区，避免“基本信息”被
# 当成上一条经历的正文。它们仍由全局字段/正文启发式解析。
_RESET_SECTION_ALIASES = (
    "基本信息",
    "基本资料",
    "个人信息",
    "个人概况",
    "联系方式",
    "contact",
    "personal information",
)
